# Generated by Django 5.1.5 on 2025-03-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Тут должен быть название задачи', max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Тут должен быть описание задачи', verbose_name='Описание')),
                ('is_completed', models.BooleanField(default=True, verbose_name='Завершон?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to='image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
