# Generated by Django 5.1.5 on 2025-02-28 13:08

import apps.utils
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Тут должен быть название задачи', max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Тут должен быть описание задачи', verbose_name='Описание')),
                ('is_completed', models.BooleanField(default=True, verbose_name='Завершон?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='TodoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=apps.utils.get_todo_upload_path, verbose_name='Изображение')),
                ('position', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_image', to='todos.todo', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['position'],
            },
        ),
    ]
